export interface IUser {
    about_self?: string,
    avatar_url?: string,
    avatar_url_big_thumbnail?: string,
    avatar_url_thumbnail?: string,
    birthday?: string,
    country?: string,
    created_at?: string,
    credits?: number,
    disabled?: 1 | 0,
    email?: string,
    email_verified_at?: any,
    gender?: 'male' | 'female',
    id?: number,
    is_confirmed_user?: 1 | 0,
    is_in_top?: 1 | 0,
    is_new_avatar?: 1 | 0,
    is_premium?: 1 | 0,
    last_online?: string,
    name?: string,
    premium_expire?: any,
    prompt_career_id?: any,
    prompt_finance_state_id?: any,
    prompt_relationship_id?: any,
    prompt_source_id?: any,
    prompt_target_id?: any,
    prompt_want_kids_id?: any,
    state?: string,
    tags?: any,
    top_expire?: any,
    type?: any,
    updated_at?: string,
    profile_photo?: any[],
    age?: number
}