export type paidActionTypes = 
'SEND_CHAT_MESSAGE' |
'SEND_CHAT_STICKER' | 
'SEND_CHAT_PHOTO' |
'SEND_CHAT_GIFT' |
'SEND_CHAT_VIDEO' |
'SEND_MAIL_MESSAGE' |
'SEND_MAIL_STICKER' | 
'SEND_MAIL_GIFT' |
'OPEN_CHAT_PHOTO' |
'OPEN_CHAT_VIDEO' |
'OPEN_MAIL_TEXT' |
'OPEN_MAIL_PHOTO' |
'OPEN_MAIL_VIDEO' |
'OPEN_MAIL_PHOTO_CENSORED' |
'OPEN_MAIL_VIDEO_CENSORED'